sudo: false
install: true

os:
  - linux

language: python
python:
  - "2.7"

branches:
  only:
  - master

before_install:
  - sudo apt-get -qqy update
  - sudo apt-get install -y python python-pip

before_script:
  - sudo pip install -r requirements.txt
  - sudo pip install pylint

script:
  - make test && make clean && make && ./sipd -t
  - find . -type f -iname "*.py" -exec pylint "{}" \;

matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "nightly"
