sudo: false
install: true

os:
  - linux

language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

branches:
  only:
  - master

before_install:
  - sudo apt-get -qqy update
  - sudo apt-get install -y python3 python3-pip

before_script:
  - sudo pip install -r requirements.txt

script:
  - # make test && make clean && make && ./sipping -t
  - # find . -type f -iname "*.py" -exec pylint "{}" \;

matrix:
  allow_failures:
    - python: "3.3"
    - python: "nightly"
