sudo: false
install: true

os:
  - linux

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"

branches:
  only:
  - master

before_install:
  - sudo apt-get -qqy update
  - sudo apt-get install -y python3 python3-pip

before_script:
  - sudo pip install pytest

script:
  - true

matrix:
  allow_failures:
    - python: "nightly"
