---
project:
  name: sipd
  description: active-recording Session Initiation Protocol daemon
  license: MIT
  repository: https://github.com/initbar/sipd

server:
  host: '127.0.0.1'
  port: 5060
  worker: 1

sip:
  version: '2.0'
  headers:
    Accept: application/sdp
    Accept-Language: en
    Allow:
    - ACK
    - BYE
    - CANCEL
    - INVITE
    - OPTIONS
    - REFER
    - UPDATE
    Max-Forwards: 70
    Min-SE: 1800
    Require: timer
    Server: SIPd
    Session-Expires: 1800;refresher=uac
    Supported: timer

sdp:
  headers:
    v: 0
    t: 0 0
    c: IN IP4 %s
    s: phone-call
    m: audio %s RTP/AVP 0 8 18 96
    a:
    - rtpmap:0 PCMU/8000
    - rtpmap:8 PCMA/8000
    - rtpmap:18 G729/8000
    - rtpmap:96 telephone-event/8000
    - fmtp:96 0-15
    - recvonly
    - ptime:20
    - maxptime:1000

rtp:
  handlers:
  - enabled: false
    host: 127.0.0.1
    port: 5900
    active: true
    standby: false

garbage_collector:
  call_max_lifetime_in_sec: 3600
  event_loop_speed_in_sec: 0.01

log:
  level: INFO
  disk:
    enabled: false
    path: "./logs"
    name: sipd.log
    total_days_preserved: 7
